name: update releases

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  build_page:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - run: |
          pip install pygithub
          sudo apt-get -y install pandoc
        shell: bash
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          set-safe-directory: true
      - name: gen releases page
        env:
          TOKEN: ${{ github.token }}
        run: |
          ./gen_releases.py
          pandoc --from=markdown -t html index.rst -o index.html
        shell: bash
      - uses: EndBug/add-and-commit@v9
        with:
          add: index.html
          message: update releases listing
          committer_name: GitHub Actions
          committer_email: actions@github.com
      - name: push last release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh auth setup-git
          git push origin main
        shell: bash
